### ISSUE TITLE
Change project name and project URL

### ISSUE THREAD

**Issue by jardinetsouffleton** [corail-research/SeaPearlZoo.jl#57]
In order to add SeaPearlZoo to the julia package registry, we need to:

- Change the project's name to SeaPearlZoo.jl
- Change the project's URL to https://github.com/corail-research/SeaPearlZoo.jl

This way, the JuliaRegistrator bot will be able to create new versions of SeaPearlZoo automatically. Otherwise, we need to reach out to someone to create new versions.

**Comment by qcappart** [comment]
Resolved. :-)
